amazing_amazon/config/routes.rb
Rails.application.routes.draw do
  get 'admin/panel'
  
  root "products#index"
  
  get "/home" => "welcome#home"
  get "/about" => "welcome#about"
  get "/contact_us" => "welcome#contact_us"
  get "/support_me" => "welcome#donate"
  get "/thank_you" => "welcome#thank_you"
  get "/favourites_products" => "products#favourite_products"
  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post],
  )

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :products do
    resource :favourites, only: [:create]
    delete '/favourites/:id', to: 'favourites#destroy', as: :remove_favourite
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
      resources :votes, only: [:create, :update, :destroy]
    end
    post '/reviews/:id', to: 'reviews#unhide', as: :review_unhide
  end


  # In Rails the namespace method routes in the below code will make your 
  # app look in a directory called api, in a sub directory called v1, for 
  # a fill called products_controller.rb 
  # i.e. <app_of_name>/app/controllers/api/v1/products_controller.rb

  # The option 'defaults: { format: :json }' will set 'json' as
  # the default response format for all routes contained within
  # the block instead of rails regulare default format of HTML.

  namespace :api, defaults: { format: :json } do # we can set default response format of the block
    namespace :v1 do
      resources :products, only:[:index, :show, :create, :destroy, :update]
      resource :session, only:[:create, :destroy]
      resources :users, only: [:create] do
        get :current, on: :collection
        resources :reviews
      end
    end
    match "*unmatched_route", to: "application#not_found", via: :all
  end


  resources :news_articles

  default_url_options :host => "http://localhost:3000"

end

amazing_amazon/app/views/shared/_flash_messages.html.erb
<div >
  <% flash.each do |type, message| %>
    <div <%= type %>>
      <%= message %>
    </div>
  <% end %>
</div>

amazing_amazon/app/views/shared/_navbar.html.erb
<nav class='navbar navbar-light bg-light mb-5'>
  <%= link_to "Home", home_path %> 
  <%= link_to "Products", products_path %> 
  <%= link_to "New Product", new_product_path %> 
  <%= link_to "About", about_path %> 
  <%= link_to "Contact Us", contact_us_path %> 
  
  <% if can? :read, :admin %>
    <%= link_to "ADMIN", admin_panel_path %>
  <% end %>

  <% if user_signed_in? %> 
    <%= link_to "Favourite Products", favourites_products_path %>
    <span class='text-muted mr-3'>Hello, <%= current_user.full_name %></span>
    <%= button_to "Log Out", session_path, method: :delete, class: "btn btn-danger" %>
  <% else %>
      <%= link_to "Log In", new_session_path, class: "btn btn-success" %>
      <%= link_to "Sign Up", new_user_path, class: "btn btn-success" %>
  <% end %>

</nav>