amazing_amazon/config/routes.rb
Rails.application.routes.draw do
  get 'admin/panel'
  
  root "products#index"
  
  get "/home" => "welcome#home"
  get "/about" => "welcome#about"
  get "/contact_us" => "welcome#contact_us"
  get "/support_me" => "welcome#donate"
  get "/thank_you" => "welcome#thank_you"
  get "/favourites_products" => "products#favourite_products"
  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post],
  )

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :products do
    resource :favourites, only: [:create]
    delete '/favourites/:id', to: 'favourites#destroy', as: :remove_favourite
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
      resources :votes, only: [:create, :update, :destroy]
    end
    post '/reviews/:id', to: 'reviews#unhide', as: :review_unhide
  end


  # In Rails the namespace method routes in the below code will make your 
  # app look in a directory called api, in a sub directory called v1, for 
  # a fill called products_controller.rb 
  # i.e. <app_of_name>/app/controllers/api/v1/products_controller.rb

  # The option 'defaults: { format: :json }' will set 'json' as
  # the default response format for all routes contained within
  # the block instead of rails regulare default format of HTML.

  namespace :api, defaults: { format: :json } do # we can set default response format of the block
    namespace :v1 do
      resources :products, only:[:index, :show, :create, :destroy, :update]
      resource :session, only:[:create, :destroy]
      resources :users, only: [:create] do
        get :current, on: :collection
        resources :reviews
      end
    end
    match "*unmatched_route", to: "application#not_found", via: :all
  end


  resources :news_articles

  default_url_options :host => "http://localhost:3000"

end

amazing_amazon/app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, -> { order("updated_at DESC") }, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favourite_users, through: :favourites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :user


  validates(:title,
          presence: { message: "Title must be provided" },
          :uniqueness => { :case_sensitive => false })
  validates :price, numericality: { greater_than: 0 }
  validates :description, presence: { message: "Description must be provided" }, length: { minimum: 10 }
  before_validation :set_default_price, :capitalize_title
  DEFAULT_PRICE = 1

  def tag_names
    self.tags.map(&:name).join(", ")
  end

  # Appending = at the end of a method name, allows to implement
  # a "setter". A setter is a method that is assignable.
  # Example:
  # p.tag_names = "stuff,yo"
  # The code in the example above would call the method we wrote
  # below where the value on the right-hand side of the = would
  # become the argument to the method.
  # This is similar to implementing an `attr_writer`.
  def tag_names=(rhs)
    self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
      Tag.find_or_initialize_by(name: tag_name)
    end
  end

  private

  def capitalize_title
    self.title.capitalize!
  end

  def set_default_price
      self.price ||= DEFAULT_PRICE
  end
end

amazing_amazon/app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController
  # created with:
  # $ rails g controller api/v1/products --skip-template-engine

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_product,only:[:show, :destroy, :update]
  before_action :authorize!, only: [:update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  rescue_from ActiveRecord::RecordInvalid, with: :record_invalid


  # postman requests for testing

  # product index
  #  - localhost:3000/api/v1/products
  #  - method: get

  # product show
  #  - localhost:3000/api/v1/products/<id of product i.e. 103>
  #  - method: get

  # product create
  #  - http://localhost:3000/api/v1/products
  #  - method: post
  #  - header: 
  #    - key: Content-Type, value: application/json
  #  - body: 
  #     {
  #       "title": "****** postman ********",
  #       "description": "afs fa fda sf fafs fsf s",
  #       "price": 1,
  #       "tag_names": "tag1,tag2,tag3"
  #     }

  # product update
  #  - localhost:3000/api/v1/products/<id of product i.e. 103>
  #  - method: update
  #  - header: 
  #    - key: Content-Type, value: application/json
  #  - body: 
  #     {
  #       "title": "****** updated postman ********",
  #       "description": "this has been updated through postman",
  #       "price": 1,
  #       "tag_names": "tag1,tag2,tag3"
  #     }

  # product delete
  #  - localhost:3000/api/v1/products/<id of product i.e. 103>
  #  - method: delete
  def index
    products = Product.order created_at: :desc 
    # or # products = Product.order(created_at: :desc)
    render(json: products, each_serializer: ProductCollectionSerializer)    
    # or # render json: products, each_serializer: ProductCollectionSerializer    
  end

  def show
    # each_serializer doesn't work because @product isn't an array.
      render json: @product
  end

  def create
    product = Product.new product_params
    product.user = current_user

    if product.save
      render json:{ id: product.id }
    else
      render(
        json:{ errors: product.errors },
        status: 422 # Unprocessable Entity
      )
    end
  end

  def update
    if @product.update product_params
      render json: { id: @product.id }
    else
      render(
        json: { errors: @product.errors },
        status: 422 # status: Unprocessable Entity
      )
    end
  end

  def destroy
    if @product.destroy
      render(json: { status: 200 }, status: 200) # status: success
    else
      render(json: { status: 422, errors: @product&.errors }, status: 422) # status: Unprocessable Entity
    end
  end

  protected

  def record_invalid(error)
    invalid_record = error.record
    errors = invalid_record.errors.map do |errorObject|
      {
        type: error.class.to_s,
        record_type: invalid_record.class.to_s,
        field: errorObject.attribute,
        message: errorObject.options[:message],
      }
    end
    render(
      json: { status: 422, errors: errors },
      status: 422,
    )
  end

  def record_not_found(error)
    render(
      status: 404,
      json: {
        errors: [
          {
            type: error.class.to_s,
            message: error.message,
          },
        ],
      },
    )
  end

  private

  def find_product
     @product ||= Product.find params[:id]
  end

  def product_params
    p params
    params.permit(:title, :description)
  end

  def authorize!
    render(json: { status: 401 }, status: 401) unless can? :crud, @product
  end

end

amazing_amazon/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, except: [:create, :index, :favourite_products]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:tag]
      @tag = Tag.find_or_initialize_by(name: params[:tag])
      @products = @tag.products.order(created_at: :DESC)
    else
      @products = Product.order(created_at: :DESC)
    end
  end

  def new
  end

  def create
    @product = Product.new(product_params)
    @product.user = @current_user

    # @product.save
    if @product.save

      # ProductMailer.notify_product_owner(@product).deliver
      ProductMailer.delay(run_at: 2.minutes.from_now).notify_product_owner(@product)
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @reviews = @product.reviews
    @review = Review.new
  end

  def destroy
    # bellow if can? statment prevents a hacker from typing the destroy command in the url
    # to see if passes.
    if !(can? :delete, @product)
      redirect_to @product, error: "not authorized"
      # redirect_to product_path(@product), error: "not authorized" -- also works
    end

    @product.destroy
    redirect_to products_path
  end

  def edit
  end

  def update
    # bellow if can? statment prevents a hacker from typing the update command in the url
    # to see if passes.
    if !(can? :update, @product)
      redirect_to @product, error: "not authorized"
      # redirect_to product_path(@product), error: "not authorized" -- also works
    end
    @product.update(product_params)

    if @product.save
      redirect_to product_path(@product)
    else
      render :edit
    end

  end

  def favourite_products
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :tag_names)
  end

  def load_product
    if params[:id].present?
      @product = Product.find(params[:id])
    else
      @product = Product.new
    end
  end

end

amazing_amazon/app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
  # created with:
  # $ rails g controller api/v1/products

  
end

amazing_amazon/app/helpers/products_helper.rb
module ProductsHelper
end

amazing_amazon/app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |f| %>
  <div >
    <%= f.label :title %>
    <br>
    <%= f.text_field(:title, placeholder: "Product Name") %>
  </div>
  <br>
  <div >
    <%= f.label :description %>
    <br>
    <%= f.text_area(:description, cols: 50, rows: 5, placeholder: "Provide Description") %>
  </div>
  <br>
  <div>
    <%= f.label :price %>
    <br>
    <%= f.number_field(:price, min: 0, placeholder: "Enter Price", step: :any) %>
  </div>
  <br>
  <div class='form-group'>
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names %>
  </div>
  <br>
<% if @product.new_record? %>
    <%= f.submit("Create") %>
  <% else %>
    <%= f.submit("Update") %>
  <% end %>
<% end %>

<script>
  $(function(){
    $('#product_tag_names').selectize({
      delimeter: ',',
      persist: false,
      labelField: 'name',
      valueField: 'name',
      searchField: 'name',
      options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
      // The above line selects only names from tags table and converts them to
      // a json array of objects
      // without including ids and makes sure its a safe_html string
      // options: [{"name": "first tag"}, {"name": "second tag"}, {"name": "third tag"},
      //           {"name": "fourth tag"}, {"name": "fifth tag"}, ...]
      create: function(input) {
        return {
          name: input 
        }
      }
    });
  });
</script> 

amazing_amazon/app/views/products/edit.erb
<h1>Editing <%= @product.title %></h1>

<%= render 'form' %>
<p><%= link_to "Back", products_path %></p>

amazing_amazon/app/views/products/favourite_products.erb
<h1>My favourite products</h1>

<% @current_user.favourite_products.each do |product| %>
    <%= link_to product_path(product) do %>
      <ul>
        <li><%= product.id %>: <%= product.title %>
        <br>price: <%= number_to_currency product.price %></li>
      </ul>
    <% end %>
  <% end %>
  

amazing_amazon/app/views/products/index.erb
<h1>This is the index of products</h1>

<p><%= link_to "Add Product", new_product_path %></p>

<% if @tag.present? %>
  <h6>
    Showing products tagged by:
    <span>
      <%= @tag.name %>
    </span>
  </h6>
<% end %>

<% @products.each do |product| %>
  <%= link_to product_path(product) do %>
    <ul>
      <li><%= product.id %>: <%= product.title %>
      <br>price: <%= number_to_currency product.price %></li>
    </ul>
  <% end %>
<% end %>

amazing_amazon/app/views/products/new.erb
<h1>Add a new product</h1>

<%= render 'form' %>
<p><%= link_to "Back", products_path %></p>

amazing_amazon/app/views/products/show.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %>
<br>Price: <%= number_to_currency @product.price %></p>
<p>
<small class='text-muted'>
  sold by <em><%= @product.user.full_name %></em>
</small>
  <p>Tags:</p>
   <% unless @product.tags.empty? %>
    <div>
      <% @product.tags.each do |tag| %>
        <%= link_to(
            tag.name,
            products_path(tag: tag.name)
        ) %>
      <% end %>
    </div>
  <% end %>
  </p>
  <% if can? :update, @product %>
    <%= link_to "Edit", edit_product_path(@product) %>
  <% end %>
  <% if can? :delete, @product %>
    <br/>
    <%= button_to "Delete", @product, method: :delete %>
  <% end %>
  
  <p>
    <% if user_signed_in? %>
        <% favourite = current_user.favourites.find_by_product_id(@product.id) %>
        <% if favourite %>
          <%= button_to "Remove from favourite", product_remove_favourite_path(@product.id,favourite.id), method: :delete %>
        <% else %>
          <%= button_to "Add to favourite", product_favourites_path(@product), method: :post %>
        <% end %>
    <% end %>
  </p>

  <p><%= link_to "Back", products_path %></p>

 <h4>Write your review</h4>

 <ul>
 <% if @review.errors.any? %>
     <% @review.errors.full_messages.each do |msg|%>
     <li><%= msg %></li>
     <% end %>
 <% end %>
 </ul>
 <%= form_with(model: [@product, @review]) do |form|%>
 <div>
     <%= form.label :body%>
     <%= form.text_area :body%>
 </div>
 <div>
     <%= form.label :rating%>
     <%= form.number_field :rating%>
 </div>
 <div>
    <%= form.label :is_hidden %>
    <%= form.check_box :is_hidden %>

 </div>
 <%= form.submit %>
 <% end %>

 
 <h4 class="mt-3">Reviews</h4>
<% @product.reviews.each do |review| %>
  <div class='shadow-sm p-3 mb-1 bg-white rounded'>   
      
    <% if review.is_hidden && (can? :update, review) %>
      <%= button_to("UnHide", product_review_unhide_path(@product.id, review.id), method: 'post' ) %>
    <% end %>

    <p class='review-body' style="<%= review.is_hidden ? "color: grey" : "" %>"><%= review.body %></p>    
    
    <small class='font-weight-lighter d-inline-block text-muted'>by <%= review.user.full_name %></small>
    
    <%= button_to("Delete", product_review_path(@product.id, review.id), method: :delete, 
      class: "btn btn-danger btn-sm",
      data: { confirm: "Are you sure?" }) %>

    <p>
      <% if user_signed_in? %>
          <% like = current_user.likes.find_by_review_id(review) %>
          <% if like %>
            <%= button_to "Unlike", like_path(like), method: :delete %>
          <% else %>
            <%= button_to "Like", product_review_likes_path(@product, review.id), method: :post %>
          <% end %>
      <% end %>
    (<%= pluralize review.likes.count, 'like' %>)
    </p>
    
      <% vote = review.votes.find_by(user: current_user) %>
      <span class="vote-widget">
        <% if vote.nil? %>
          <%= button_to 'vote up', product_review_votes_path(@product, review, is_up: true), method: :post %>
          (<%= review.vote_total %>)
          <%= button_to 'vote down', product_review_votes_path(@product, review, is_up: false), method: :post %>
        <% elsif vote.is_up? %>
          <%= button_to 'vote up', product_review_vote_path(@product, review, vote), method: :delete, class: 'active' %>
          (<%= review.vote_total %>)
          <%= button_to 'vote down', product_review_vote_path(@product, review, vote, is_up: false), method: :patch %>
        <% else %>
          <%= button_to 'vote up', product_review_vote_path(@product, review, vote, is_up: true), method: :patch %>
          (<%= review.vote_total %>)
          <%= button_to 'vote down', product_review_vote_path(@product, review, vote), method: :delete, class: 'active' %>
        <% end %>
      </span>
  </div>
<% end %>